Add GitHub actions
AmbiML/iree-rv32-springbok pull request #3
Opened 2022-04-28 09:56 UTC by PiotrZierhoffer

This PR adds a simple GitHub Actions test running the flow from README using [Tuttest](https://github.com/antmicro/tuttest/).

I explicitly skipped running Renode interactively, but otherwise this runs all other commands.

Additionaly I added missing Python dependencies and reduced some wget logs (polluting CI very heavily)

2022-04-28 17:54 UTC, adamjesionowski commented on .github/workflows/springbok.yml
> +    - cron: '0 23 * * *' # run daily at 23:00 (UTC)
I imagine we just want on push rather than daily.

2022-04-28 18:56 UTC, hcindyl requested changes

2022-04-28 18:56 UTC, hcindyl commented on README.md
> +pip install lit wget numpy Pillow
Please rebase. The python requirement has been converted into a list in https://github.com/AmbiML/iree-rv32-springbok/pull/2.

2022-04-28 21:06 UTC, hcindyl commented on .github/workflows/springbok.yml
> +    runs-on: ubuntu-20.04
Ubuntu Focal's CMake is on 3.16.3. It will fall on building IREE (CMake >= 3.17). Probably want to change the base to Ubuntu 22.04.

2022-04-29 04:46 UTC, hcindyl commented on .github/workflows/springbok.yml
> +    runs-on: ubuntu-20.04
virtual-environments side-loads latest `cmake` when building the ubuntu 20.04 image. https://github.com/actions/virtual-environments/blob/9f9633ce6f0385f75fd3a66db9a50c7902e4a686/images/linux/ubuntu2004.json#L205, so it runs on cmake 3.23 instead.

2022-04-29 19:50 UTC, adamjesionowski approved these changes

2022-04-29 19:50 UTC, adamjesionowski approved these changes

2022-04-29 19:53 UTC, adamjesionowski approved these changes

2022-04-29 19:53 UTC, merged